---
title: "Resources"
---

## Software packages
1. R: `rdecision`: <https://cran.r-project.org/web/packages/rdecision/index.html>
2. Python: `pyAgrum`: <https://pyagrum.gitlab.io/> 
3. Julia: `DecisionProgramming.jl`: <https://gamma-opt.github.io/DecisionProgramming.jl/dev/>  
4. Julia: `Agents.jl`: <https://juliadynamics.github.io/Agents.jl/stable/>

## Primer on Medical Decision Analysis (5 part series)
1. Detsky, A. S., G. Naglie, M. D. Krahn, D. Naimark, and D. A. Redelmeier. “Primer on Medical Decision Analysis: Part 1--Getting Started.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 17, no. 2 (1997): 123–25. <https://doi.org/10.1177/0272989X9701700201>.
2. Detsky, A. S., G. Naglie, M. D. Krahn, D. A. Redelmeier, and D. Naimark. “Primer on Medical Decision Analysis: Part 2--Building a Tree.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 17, no. 2 (1997): 126–35. <https://doi.org/10.1177/0272989X9701700202>.
3. Naglie, G., M. D. Krahn, D. Naimark, D. A. Redelmeier, and A. S. Detsky. “Primer on Medical Decision Analysis: Part 3--Estimating Probabilities and Utilities.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 17, no. 2 (1997): 136–41. <https://doi.org/10.1177/0272989X9701700203>.
4. Krahn, M. D., G. Naglie, D. Naimark, D. A. Redelmeier, and A. S. Detsky. “Primer on Medical Decision Analysis: Part 4--Analyzing the Model and Interpreting the Results.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 17, no. 2 (1997): 142–51. <https://doi.org/10.1177/0272989X9701700204>.
5. Naimark, D., M. D. Krahn, G. Naglie, D. A. Redelmeier, and A. S. Detsky. “Primer on Medical Decision Analysis: Part 5--Working with Markov Processes.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 17, no. 2 (1997): 152–59. <https://doi.org/10.1177/0272989X9701700205>.

## Individual articles
1. Owens, D. K., R. D. Shachter, and R. F. Nease. “Representation and Analysis of Medical Decision Problems with Influence Diagrams.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 17, no. 3 (1997): 241–62. <https://doi.org/10.1177/0272989X9701700301>.
2. Nease, R. F., and D. K. Owens. “Use of Influence Diagrams to Structure Medical Decisions.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 17, no. 3 (1997): 263–75. <https://doi.org/10.1177/0272989X9701700302>.
3. Sonnenberg, F. A., and J. R. Beck. “Markov Models in Medical Decision Making: A Practical Guide.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 13, no. 4 (1993): 322–38. <https://doi.org/10.1177/0272989X9301300409>.
4. Alarid-Escudero, Fernando, Eline Krijkamp, Eva A. Enns, et al. “A Tutorial on Time-Dependent Cohort State-Transition Models in R Using a Cost-Effectiveness Analysis Example.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 43, no. 1 (2023): 21–41. <https://doi.org/10.1177/0272989X221121747>.
5. Alarid-Escudero, Fernando, Eline Krijkamp, Eva A. Enns, et al. “An Introductory Tutorial on Cohort State-Transition Models in R Using a Cost-Effectiveness Analysis Example.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 43, no. 1 (2023): 3–20. <https://doi.org/10.1177/0272989X221103163>.
6. Jalal, Hawre, Petros Pechlivanoglou, Eline Krijkamp, Fernando Alarid-Escudero, Eva Enns, and M. G. Myriam Hunink. “An Overview of R in Health Decision Sciences.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 37, no. 7 (2017): 735–46. <https://doi.org/10.1177/0272989X16686559>.
7. Williams, Claire, James D. Lewsey, Andrew H. Briggs, and Daniel F. Mackay. “Cost-Effectiveness Analysis in R Using a Multi-State Modeling Survival Analysis Framework: A Tutorial.” Medical Decision Making: An International Journal of the Society for Medical Decision Making 37, no. 4 (2017): 340–52. <https://doi.org/10.1177/0272989X16651869>.

## Recommended books
1. Duke, Annie. How to Decide: Simple Tools for Making Better Choices. Penguin Publishing Group, 2020. <https://www.annieduke.com/books/>.
2. Sox, Harold C., Michael C. Higgins, Douglas K. Owens, and Gillian Sanders Schmidler. Medical Decision Making. Third edition. John Wiley & Sons, Inc, 2024. <https://doi.org/10.1002/9781119627876>.
3. Hunink, M. G. Myriam. Decision Making in Health and Medicine. 2nd ed. With Milton C. Weinstein, Eve Wittenberg, Michael F. Drummond, Joseph S. Pliskin, John B. Wong, and Paul Glasziou. Cambridge University Press, 2014. <https://doi.org/10.1017/CBO9781139506779>.
4. Briggs, Andrew Harvey, Karl Claxton, and Mark Sculpher. Decision Modelling for Health Economic Evaluation. Repr. [d. korr. Ausg. von 2007]. Handbooks in Health Economic Evaluation Series. Oxford Univ. Press, 2011.
5. Parnell, Gregory S, Terry A. Bresnick, Eric Specking, Steven N. Tani, and Eric R. Johnson. Handbook of Decision Analysis. 2nd ed. Wiley, 2025.

